// tuna_zalo/src/pages/index/TimelinePage.jsx
import React, { useState, useEffect, useMemo, useCallback, useRef } from "react";

const API_BASE = "https://tuna-project.onrender.com/api";

export const TimelinePage = ({ onBack, onNavigateToTasks, onNavigateToDocs, onOpenScheduleModal }) => {
  const getLocalDateString = (d = new Date()) => {
    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, "0");
    const day = String(d.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
  };

  const todayStr = useMemo(() => getLocalDateString(), []);
  const [currentViewDate, setCurrentViewDate] = useState(new Date());
  const [selectedDayKey, setSelectedDayKey] = useState(todayStr);

  const [dbTimelines, setDbTimelines] = useState([]);
  const [loading, setLoading] = useState(false);
  const [isWrrGenerating, setIsWrrGenerating] = useState(false);

  // Cờ chặn vòng lặp vô tận
  const hasAutoGeneratedRef = useRef(false);

  // Toast thông báo
  const [toastMessage, setToastMessage] = useState(null);
  const showToast = (message, type = "success") => {
    setToastMessage({ message, type });
    setTimeout(() => {
      setToastMessage(null);
    }, 2800);
  };

  // State Modal Chi Tiết & Modal Thêm/Sửa
  const [viewingDetailTask, setViewingDetailTask] = useState(null);
  const [showItemModal, setShowItemModal] = useState(false);
  const [editingItem, setEditingItem] = useState(null);
  const [formData, setFormData] = useState({
    title: "",
    timeSlot: "19:30 - 20:15",
    taskType: "quiz",
    description: "",
    durationMinutes: 15,
    subject: "",
  });

  // Lấy danh tính người dùng đồng nhất
// SỬA LẠI ĐOẠN NÀY (BỎ currentUser KHỎI DEPENDENCY VÌ PROP KHÔNG CÓ)
  const currentStudentId = useMemo(() => {
    try {
      const u = JSON.parse(localStorage.getItem("user") || localStorage.getItem("user_info") || "{}");
      const id = u.student_code || u.email || u.zalo_id || u.id;
      if (id && id !== "undefined" && id !== "null") return String(id).trim();
    } catch (e) {}
    return String(localStorage.getItem("user_email") || localStorage.getItem("tuna_user_id") || "guest_user").trim();
  }, []);

  const academicProfile = useMemo(() => {
    try {
      const p = localStorage.getItem("user_academic_profile");
      return p ? JSON.parse(p) : null;
    } catch {
      return null;
    }
  }, []);

  const rawSchedules = useMemo(() => {
    try {
      const s = localStorage.getItem("user_custom_schedules");
      return s ? JSON.parse(s) : [];
    } catch {
      return [];
    }
  }, []);

  const currentWeekDays = useMemo(() => {
    const base = new Date(currentViewDate);
    const day = base.getDay();
    const diff = base.getDate() - day + (day === 0 ? -6 : 1);

    const monday = new Date(base.setDate(diff));
    const days = [];
    for (let i = 0; i < 7; i++) {
      const nextDate = new Date(monday);
      nextDate.setDate(monday.getDate() + i);
      days.push(nextDate);
    }
    return days;
  }, [currentViewDate]);

  const startDateStr = useMemo(() => getLocalDateString(currentWeekDays[0]), [currentWeekDays]);
  const endDateStr = useMemo(() => getLocalDateString(currentWeekDays[6]), [currentWeekDays]);

  const handleTaskAction = useCallback((task) => {
    const type = task.task_type || task.taskType;
    const target = task.action_target || task.actionTarget;

    if (type === "doc_study" || target === "docs") {
      if (onNavigateToDocs) onNavigateToDocs(task.subject);
      else if (onNavigateToTasks) onNavigateToTasks();
    } else {
      if (onNavigateToTasks) onNavigateToTasks();
    }
  }, [onNavigateToDocs, onNavigateToTasks]);

  // Tải danh sách lịch trình
  const fetchTimelines = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch(
        `${API_BASE}/timelines?userId=${encodeURIComponent(currentStudentId)}&startDate=${startDateStr}&endDate=${endDateStr}`,
        {
          headers: {
            "Content-Type": "application/json",
            "x-user-id": encodeURIComponent(currentStudentId),
          },
        }
      );
      const json = await res.json();
      if (json.success && Array.isArray(json.data)) {
        const formatted = json.data.map((item) => {
          let d = item.timelineDate || item.timeline_date || "";
          if (d.includes("T")) d = d.split("T")[0];
          return {
            ...item,
            timelineDate: d,
            timeline_date: d,
          };
        });
        setDbTimelines(formatted);

        // Lưu đồng bộ các ca hôm nay để widget Trang chủ đọc được ngay
        const todayItems = formatted.filter((t) => t.timelineDate === todayStr);
        localStorage.setItem("tuna_today_tasks", JSON.stringify(todayItems));
      }
    } catch (err) {
      console.error("Lỗi tải lịch trình:", err);
    } finally {
      setLoading(false);
    }
  }, [currentStudentId, startDateStr, endDateStr, todayStr]);

  // Kích hoạt thuật toán WRR
  const handleTriggerWRRPlan = useCallback(async (isAuto = false) => {
    if (isWrrGenerating) return;
    setIsWrrGenerating(true);
    try {
      const fallbackSubs = ["Cơ sở dữ liệu", "Phân tích và thiết kế HTTT", "Hệ quản trị CSDL"];
      const subs = Array.isArray(academicProfile?.subjects) && academicProfile.subjects.length > 0
        ? academicProfile.subjects
        : fallbackSubs;

      const res = await fetch(`${API_BASE}/timelines/generate-wrr-plan`, {
        method: "POST",
        headers: { 
          "Content-Type": "application/json",
          "x-user-id": encodeURIComponent(currentStudentId),
        },
        body: JSON.stringify({
          userId: currentStudentId,
          facultyMajor: academicProfile?.major || "Hệ Thống Thông Tin",
          year: academicProfile?.year || 4,
          semester: academicProfile?.semester || 1,
          subjects: subs,
          subjectLevels: academicProfile?.subjectLevels || {},
          currentGpa: Number(academicProfile?.currentGpa) || 3.0,
          goalLevel: academicProfile?.targetGoal || "KhaGioi",
          dailyPace: academicProfile?.dailyPace || 15,
          startDate: startDateStr,
        }),
      });

      const data = await res.json();
      if (data.success) {
        if (!isAuto) {
          showToast("Đã tối ưu hóa lịch tự học thành công!", "success");
        }
        await fetchTimelines();
      } else if (!isAuto) {
        showToast(data.error || "Không thể tạo lịch trình", "error");
      }
    } catch (e) {
      if (!isAuto) showToast("Lỗi kết nối máy chủ!", "error");
    } finally {
      setIsWrrGenerating(false);
    }
  }, [currentStudentId, academicProfile, startDateStr, isWrrGenerating, fetchTimelines]);

  useEffect(() => {
    fetchTimelines();
  }, [fetchTimelines]);

  useEffect(() => {
    if (!loading && dbTimelines.length === 0 && !hasAutoGeneratedRef.current) {
      hasAutoGeneratedRef.current = true;
      handleTriggerWRRPlan(true);
    }
  }, [loading, dbTimelines.length, handleTriggerWRRPlan]);

  const handleSaveItem = async (e) => {
    e.preventDefault();
    if (!formData.title.trim()) return;

    try {
      if (editingItem) {
        const res = await fetch(`${API_BASE}/timelines/${editingItem.id}`, {
          method: "PUT",
          headers: { 
            "Content-Type": "application/json",
            "x-user-id": encodeURIComponent(currentStudentId),
          },
          body: JSON.stringify(formData),
        });
        const data = await res.json();
        if (data.success) {
          await fetchTimelines();
          showToast("Cập nhật thành công!");
        }
      } else {
        const res = await fetch(`${API_BASE}/timelines`, {
          method: "POST",
          headers: { 
            "Content-Type": "application/json",
            "x-user-id": encodeURIComponent(currentStudentId),
          },
          body: JSON.stringify({
            ...formData,
            userId: currentStudentId,
            timelineDate: selectedDayKey,
            goalLevel: academicProfile?.targetGoal || "KhaGioi",
            subject: formData.subject || academicProfile?.subjects?.[0] || "Cơ sở dữ liệu",
          }),
        });
        const data = await res.json();
        if (data.success) {
          await fetchTimelines();
          showToast("Thêm ca học thành công!");
        }
      }
      setShowItemModal(false);
      setEditingItem(null);
    } catch (err) {
      showToast("Lỗi khi lưu lịch trình!", "error");
    }
  };

  const handleDeleteItem = async (e, id) => {
    e.stopPropagation();
    if (!window.confirm("Bạn có chắc chắn muốn xóa ca học này?")) return;

    try {
      const res = await fetch(`${API_BASE}/timelines/${id}`, { 
        method: "DELETE",
        headers: { "x-user-id": currentStudentId },
      });
      const data = await res.json();
      if (data.success) {
        setDbTimelines((prev) => prev.filter((item) => item.id !== id));
        if (viewingDetailTask?.id === id) setViewingDetailTask(null);
        showToast("Đã xóa khỏi lịch trình!");
      }
    } catch (err) {
      showToast("Lỗi khi xóa ca học!", "error");
    }
  };

  const handleOpenAdd = () => {
    setEditingItem(null);
    setFormData({
      title: "",
      timeSlot: "19:30 - 20:15",
      taskType: "quiz",
      description: "",
      durationMinutes: academicProfile?.dailyPace || 15,
      subject: academicProfile?.subjects?.[0] || "Cơ sở dữ liệu",
    });
    setShowItemModal(true);
  };

  const handleOpenEdit = (e, item) => {
    e.stopPropagation();
    setEditingItem(item);
    setFormData({
      title: item.title,
      timeSlot: item.timeSlot || item.time_slot,
      taskType: item.taskType || item.task_type || "quiz",
      description: item.description || "",
      durationMinutes: item.durationMinutes || item.duration_minutes || 15,
      subject: item.subject,
    });
    setShowItemModal(true);
  };

  const handleShiftWeek = (offsetWeeks) => {
    const next = new Date(currentViewDate);
    next.setDate(next.getDate() + offsetWeeks * 7);
    setCurrentViewDate(next);
  };

  const getDayName = (dateObj) => {
    const names = ["Chủ nhật", "Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"];
    return names[dateObj.getDay()];
  };

  const dayScheduleData = useMemo(() => {
    let matchedClasses = rawSchedules.filter((s) => s.date === selectedDayKey);
    if (matchedClasses.length === 0 && rawSchedules.length > 0) {
      const [y, m, d] = selectedDayKey.split("-").map(Number);
      const dayOfWeek = new Date(y, m - 1, d).getDay();
      matchedClasses = rawSchedules.filter((s) => {
        if (!s.date) return false;
        const [sy, sm, sd] = s.date.split("-").map(Number);
        return new Date(sy, sm - 1, sd).getDay() === dayOfWeek;
      });
    }

    const matchedTimelines = dbTimelines.filter((t) => {
      const d = (t.timelineDate || t.timeline_date || "").split("T")[0];
      return d === selectedDayKey;
    });

    return {
      classes: matchedClasses,
      tasks: matchedTimelines,
      totalCount: matchedClasses.length + matchedTimelines.length,
    };
  }, [selectedDayKey, rawSchedules, dbTimelines]);

  const targetGoalName = academicProfile?.targetGoal === "HocBong" 
    ? "Mục tiêu: Săn học bổng" 
    : academicProfile?.targetGoal === "QuaMon" 
    ? "Mục tiêu: Chuẩn qua môn" 
    : "Mục tiêu: Khá / Giỏi";

  return (
    <div className="flex flex-col min-h-screen bg-[#F8FAFC] pb-24 text-slate-800 antialiased w-full relative">
      {/* Toast thông báo */}
      {toastMessage && (
        <div 
          className="fixed top-20 left-4 right-4 z-50 flex items-center justify-between p-3.5 rounded-2xl shadow-xl border animate-in slide-in-from-top duration-300 backdrop-blur-md"
          style={{
            backgroundColor: toastMessage.type === "error" ? "rgba(239, 68, 68, 0.96)" : "rgba(16, 185, 129, 0.96)",
            color: "white",
            borderColor: toastMessage.type === "error" ? "#f87171" : "#34d399",
          }}
        >
          <div className="flex items-center gap-2 min-w-0 flex-1">
            <span className="w-6 h-6 rounded-lg bg-white/20 flex items-center justify-center text-xs shrink-0">
              <i className={`bi ${toastMessage.type === "error" ? "bi-exclamation-circle-fill" : "bi-check2"} text-sm`}></i>
            </span>
            <span className="text-xs font-bold truncate leading-tight">
              {toastMessage.message}
            </span>
          </div>

          <button
            onClick={() => setToastMessage(null)}
            className="w-5 h-5 rounded-full bg-white/20 text-white flex items-center justify-center border-0 cursor-pointer shrink-0 ml-2 text-[10px]"
          >
            ✕
          </button>
        </div>
      )}

      {/* 1. Header Hero Tinh Gọn */}
      <div 
        className="bg-gradient-to-br from-[#0b57d0] via-[#1a73e8] to-[#174ea6] text-white p-4 pb-6 rounded-b-[32px] shadow-sm relative overflow-hidden select-none"
        style={{ paddingTop: "max(var(--sat, 0px), 16px)" }}
      >
        <div className="flex items-center justify-between relative z-10 mb-3">
          <button
            onClick={onBack}
            className="w-9 h-9 rounded-full bg-white/15 hover:bg-white/25 flex items-center justify-center border-0 text-white active:scale-95 transition cursor-pointer"
          >
            <i className="bi bi-chevron-left font-black text-xs"></i>
          </button>

          <div className="flex items-center gap-1.5 shrink-0">
            <button
              onClick={handleOpenAdd}
              className="h-8 px-2.5 bg-white text-[#0b57d0] rounded-xl text-[11px] font-black shadow-xs active:scale-95 transition border-0 cursor-pointer flex items-center gap-1 whitespace-nowrap"
            >
              <i className="bi bi-plus-lg text-[10px]"></i>
              <span>Thêm lịch</span>
            </button>

            <button
              onClick={() => handleTriggerWRRPlan(false)}
              disabled={isWrrGenerating}
              className="h-8 px-2.5 bg-emerald-500 hover:bg-emerald-600 text-white rounded-xl text-[11px] font-black shadow-xs active:scale-95 transition border-0 cursor-pointer flex items-center gap-1 whitespace-nowrap"
            >
              {isWrrGenerating ? (
                <span className="spinner-border spinner-border-sm text-[9px]"></span>
              ) : (
                <i className="bi bi-arrow-repeat text-[10px]"></i>
              )}
              <span>Tối ưu WRR</span>
            </button>

            <button
              onClick={onOpenScheduleModal}
              className="w-8 h-8 rounded-full bg-white/15 hover:bg-white/25 flex items-center justify-center border-0 text-white active:scale-95 transition cursor-pointer shrink-0"
              title="Thời khóa biểu trường"
            >
              <i className="bi bi-calendar3 text-xs"></i>
            </button>
          </div>
        </div>

        <div className="relative z-10 space-y-1">
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-full bg-white/20 text-white text-[10px] font-bold">
              {academicProfile?.major || "Hệ Thống Thông Tin"}
            </span>
            <span className="text-blue-100 text-[11px] font-medium">
              {targetGoalName}
            </span>
          </div>
          <h2 className="text-[18px] font-black m-0 tracking-tight text-white leading-tight">
            Lịch Trình Tự Học Thông Minh
          </h2>
        </div>
      </div>

      {/* 2. Dải Chọn Ngày Trong Tuần (Lịch Trình Ngang) */}
      <div className="px-4 -mt-3 relative z-20">
        <div className="bg-white rounded-2xl p-2.5 shadow-sm border border-slate-200/80">
          <div className="flex items-center justify-between px-1 mb-2">
            <button
              onClick={() => handleShiftWeek(-1)}
              className="w-6 h-6 rounded-lg bg-slate-100 flex items-center justify-center border-0 text-slate-500 active:scale-95 cursor-pointer hover:bg-slate-200"
            >
              <i className="bi bi-chevron-left text-[11px]"></i>
            </button>
            <span className="text-[11.5px] font-black text-slate-700">
              Tuần {startDateStr.split("-").reverse().slice(0, 2).join("/")} – {endDateStr.split("-").reverse().slice(0, 2).join("/")}
            </span>
            <button
              onClick={() => handleShiftWeek(1)}
              className="w-6 h-6 rounded-lg bg-slate-100 flex items-center justify-center border-0 text-slate-500 active:scale-95 cursor-pointer hover:bg-slate-200"
            >
              <i className="bi bi-chevron-right text-[11px]"></i>
            </button>
          </div>

          <div className="grid grid-cols-7 gap-1 text-center">
            {currentWeekDays.map((d, idx) => {
              const dKey = getLocalDateString(d);
              const isSelected = dKey === selectedDayKey;
              const isToday = dKey === todayStr;
              const isSunday = d.getDay() === 0;

              return (
                <div
                  key={idx}
                  onClick={() => setSelectedDayKey(dKey)}
                  className={`py-2 rounded-xl transition cursor-pointer flex flex-col items-center justify-center relative ${
                    isSelected
                      ? "bg-[#0b57d0] text-white shadow-xs"
                      : isToday
                      ? "bg-blue-50 text-[#0b57d0] font-bold"
                      : "hover:bg-slate-50 text-slate-700"
                  }`}
                >
                  <span className={`text-[9.5px] font-bold mb-0.5 ${isSelected ? "text-blue-100" : isSunday ? "text-rose-500" : "text-slate-400"}`}>
                    {isSunday ? "CN" : `T${d.getDay() + 1}`}
                  </span>
                  <span className="text-[13px] font-black leading-none">{d.getDate()}</span>
                  {isToday && !isSelected && (
                    <span className="w-1 h-1 rounded-full bg-[#0b57d0] mt-1"></span>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* 3. Danh Sách Sự Kiện Hôm Nay / Ngày Đang Chọn */}
      <div className="p-4 space-y-3 flex-1">
        <div className="flex items-center justify-between px-1">
          <div className="flex items-center gap-2">
            <h4 className="text-xs font-black text-slate-900 m-0">
              {getDayName(new Date(selectedDayKey.replace(/-/g, "/")))}, {selectedDayKey.split("-").reverse().join("/")}
            </h4>
            {selectedDayKey === todayStr && (
              <span className="px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-800 text-[9.5px] font-black">
                Hôm nay
              </span>
            )}
          </div>
          <span className="text-[11px] font-bold text-slate-400">
            {dayScheduleData.totalCount} ca học
          </span>
        </div>

        {loading ? (
          <div className="py-12 text-center text-xs font-bold text-slate-400">
            <span className="spinner-border spinner-border-sm text-[#0b57d0] me-2"></span>
            Đang tải dữ liệu ca học...
          </div>
        ) : dayScheduleData.totalCount === 0 ? (
          <div className="bg-white rounded-2xl p-6 text-center border border-slate-200/80 shadow-2xs space-y-3">
            <div className="w-12 h-12 rounded-xl bg-slate-50 text-slate-400 flex items-center justify-center text-xl mx-auto">
              <i className="bi bi-calendar-check"></i>
            </div>
            <div>
              <h5 className="text-xs font-black text-slate-800 m-0">Không có ca học nào trong ngày</h5>
              <p className="text-[11px] text-slate-400 m-0 mt-0.5">
                Bấm "Tối ưu WRR" để tự động xếp lịch tự học cho cả tháng.
              </p>
            </div>
            <button
              onClick={() => handleTriggerWRRPlan(false)}
              className="px-4 py-2 bg-[#0b57d0] hover:bg-blue-700 text-white rounded-xl text-xs font-bold border-0 cursor-pointer active:scale-95 transition"
            >
              Chạy thuật toán WRR
            </button>
          </div>
        ) : (
          <div className="space-y-3">
            {/* 3.1. Lớp học chính khóa */}
            {dayScheduleData.classes.length > 0 && (
              <div className="space-y-2">
                <span className="text-[10px] font-black text-blue-700 uppercase px-1 flex items-center gap-1">
                  <i className="bi bi-building"></i> Lớp học chính khóa
                </span>

                {dayScheduleData.classes.map((item) => (
                  <div
                    key={item.id}
                    onClick={onOpenScheduleModal}
                    className="bg-white rounded-2xl p-3 shadow-xs border border-slate-200/80 border-l-[4px] border-l-[#0b57d0] flex items-center justify-between cursor-pointer hover:border-blue-300 transition"
                  >
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <span className="px-2 py-0.5 bg-blue-50 text-[#0b57d0] font-black text-[9.5px] rounded-md">
                          {item.category === "exam" ? "Lịch thi" : "Chính khóa"}
                        </span>
                        <span className="text-[11px] font-bold text-slate-500">
                          {item.time || "07:30 - 09:50"}
                        </span>
                      </div>
                      <h5 className="font-black text-xs text-slate-900 m-0">
                        {item.title}
                      </h5>
                      <p className="text-[11px] text-slate-400 m-0">
                        Phòng {item.room || "C201"} • {item.teacher || "Giảng viên bộ môn"}
                      </p>
                    </div>
                    <i className="bi bi-chevron-right text-slate-300 text-xs"></i>
                  </div>
                ))}
              </div>
            )}

            {/* 3.2. Ca tự học: GIAO DIỆN TỐI GIẢN CHỐNG TRÀN CHỮ */}
            {dayScheduleData.tasks.length > 0 && (
              <div className="space-y-2">
                <span className="text-[10px] font-black text-slate-500 uppercase px-1 flex items-center gap-1">
                  <i className="bi bi-lightning-charge-fill text-amber-500"></i> Ca rèn luyện trong ngày
                </span>

                {dayScheduleData.tasks.map((task) => {
                  const isDone = task.isCompleted || task.is_completed || localStorage.getItem(`daily_completed_date_${task.subject}`) === selectedDayKey;
                  const isDoc = task.task_type === "doc_study" || task.taskType === "doc_study";
                  const isQuiz = task.task_type === "quiz" || task.taskType === "quiz";

                  return (
                    <div
                      key={task.id}
                      onClick={() => setViewingDetailTask(task)}
                      className="bg-white rounded-2xl p-3.5 shadow-xs border border-slate-200/80 hover:border-blue-300 active:scale-[0.99] transition cursor-pointer flex flex-col gap-2 relative overflow-hidden"
                    >
                      {/* HÀNG 1: CHỈ GIỮ 2 PHẦN TỬ HAI ĐẦU ĐỂ KHÔNG BAO GIỜ BỊ ĐÈ CHỮ */}
                      <div className="flex items-center justify-between gap-2">
                        <span
                          className={`px-2 py-0.5 font-black text-[10px] rounded-md shrink-0 whitespace-nowrap ${
                            isDone
                              ? "bg-emerald-50 text-emerald-700"
                              : isDoc
                              ? "bg-amber-50 text-amber-700"
                              : isQuiz
                              ? "bg-indigo-50 text-indigo-700"
                              : "bg-purple-50 text-purple-700"
                          }`}
                        >
                          {isDone ? "✓ Hoàn thành" : isDoc ? "Tài liệu" : isQuiz ? "Luyện đề" : "Flashcard"}
                        </span>

                        <span className="text-[10.5px] font-bold text-slate-500 bg-slate-100 px-2 py-0.5 rounded-md truncate max-w-[170px] text-right">
                          {task.subject}
                        </span>
                      </div>

                      {/* HÀNG 2: TIÊU ĐỀ */}
                      <div>
                        <h5 className="font-black text-[13.5px] text-slate-900 m-0 leading-snug line-clamp-2">
                          {task.title}
                        </h5>
                      </div>

                      {/* HÀNG 3: NÚT THAO TÁC & GỢI Ý XEM CHI TIẾT */}
                      <div 
                        className="flex items-center justify-between pt-2 border-t border-slate-100" 
                        onClick={(e) => e.stopPropagation()}
                      >
                        <span 
                          onClick={() => setViewingDetailTask(task)}
                          className="text-[11px] font-bold text-blue-600 flex items-center gap-1 cursor-pointer hover:underline"
                        >
                          <span>Xem chi tiết</span>
                          <i className="bi bi-info-circle text-[10.5px]"></i>
                        </span>

                        <button
                          type="button"
                          onClick={() => handleTaskAction(task)}
                          className={`h-7 px-3.5 rounded-lg text-xs font-black border-0 cursor-pointer active:scale-95 transition flex items-center gap-1 shadow-xs whitespace-nowrap ${
                            isDone
                              ? "bg-slate-100 text-slate-500"
                              : isDoc
                              ? "bg-amber-400 hover:bg-amber-500 text-slate-950"
                              : "bg-[#0b57d0] hover:bg-blue-700 text-white"
                          }`}
                        >
                          <span>{isDone ? "Xem lại" : isDoc ? "Đọc bài" : "Luyện ngay"}</span>
                          <i className="bi bi-chevron-right text-[10px]"></i>
                        </button>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        )}
      </div>

      {/* 4. MODAL POPUP HIỂN THỊ CHI TIẾT CA HỌC (ĐẦY ĐỦ THÔNG TIN KHÔNG LO CHẬT) */}
      {viewingDetailTask && (
        <div 
          className="fixed inset-0 bg-slate-900/50 backdrop-blur-xs flex items-center justify-center z-50 p-4"
          onClick={() => setViewingDetailTask(null)}
        >
          <div 
            className="bg-white rounded-3xl p-5 w-full max-w-sm shadow-2xl border border-slate-100 animate-in zoom-in-95 duration-150"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Header Modal */}
            <div className="flex items-center justify-between pb-3 border-b border-slate-100">
              <span className="px-2.5 py-1 bg-blue-50 text-[#0b57d0] text-[11px] font-black rounded-lg">
                Chi Tiết Ca Rèn Luyện
              </span>
              <button
                type="button"
                onClick={() => setViewingDetailTask(null)}
                className="w-7 h-7 rounded-full bg-slate-100 flex items-center justify-center border-0 text-slate-500 hover:bg-slate-200 cursor-pointer text-xs"
              >
                ✕
              </button>
            </div>

            {/* Nội dung chi tiết */}
            <div className="py-3.5 space-y-3">
              <div>
                <span className="text-[10px] font-black uppercase text-slate-400 tracking-wider block mb-0.5">Môn học</span>
                <span className="text-xs font-black text-blue-700 bg-blue-50 px-2 py-0.5 rounded-md inline-block">
                  {viewingDetailTask.subject}
                </span>
              </div>

              <div>
                <span className="text-[10px] font-black uppercase text-slate-400 tracking-wider block mb-0.5">Nội dung nhiệm vụ</span>
                <h4 className="text-sm font-black text-slate-900 m-0 leading-snug">
                  {viewingDetailTask.title}
                </h4>
              </div>

              <div className="grid grid-cols-2 gap-2 bg-slate-50 p-2.5 rounded-xl border border-slate-100">
                <div>
                  <span className="text-[10px] font-bold text-slate-400 block">Khung giờ</span>
                  <span className="text-xs font-black text-slate-700">
                    <i className="bi bi-clock me-1 text-slate-400"></i>
                    {viewingDetailTask.time_slot || viewingDetailTask.timeSlot || "19:30 - 20:15"}
                  </span>
                </div>
                <div>
                  <span className="text-[10px] font-bold text-slate-400 block">Thời lượng</span>
                  <span className="text-xs font-black text-slate-700">
                    <i className="bi bi-hourglass-split me-1 text-slate-400"></i>
                    {viewingDetailTask.duration_minutes || viewingDetailTask.durationMinutes || 15} phút
                  </span>
                </div>
              </div>

              {viewingDetailTask.description && (
                <div>
                  <span className="text-[10px] font-black uppercase text-slate-400 tracking-wider block mb-1">Mô tả & Hướng dẫn</span>
                  <p className="text-xs text-slate-600 m-0 bg-slate-50 p-2.5 rounded-xl border border-slate-100 leading-relaxed font-medium">
                    {viewingDetailTask.description}
                  </p>
                </div>
              )}
            </div>

            {/* Footer Buttons */}
            <div className="flex items-center gap-2 pt-2 border-t border-slate-100">
              <button
                type="button"
                onClick={(e) => {
                  const t = viewingDetailTask;
                  setViewingDetailTask(null);
                  handleOpenEdit(e, t);
                }}
                className="h-9 px-3 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-xs border-0 cursor-pointer flex items-center justify-center gap-1"
                title="Chỉnh sửa"
              >
                <i className="bi bi-pencil"></i>
                <span>Sửa</span>
              </button>

              <button
                type="button"
                onClick={(e) => handleDeleteItem(e, viewingDetailTask.id)}
                className="h-9 px-3 rounded-xl bg-rose-50 hover:bg-rose-100 text-rose-600 font-bold text-xs border-0 cursor-pointer flex items-center justify-center gap-1"
                title="Xóa"
              >
                <i className="bi bi-trash3"></i>
                <span>Xóa</span>
              </button>

              <button
                type="button"
                onClick={() => {
                  const t = viewingDetailTask;
                  setViewingDetailTask(null);
                  handleTaskAction(t);
                }}
                className="flex-1 h-9 rounded-xl bg-[#0b57d0] hover:bg-blue-700 text-white font-black text-xs border-0 cursor-pointer shadow-xs active:scale-95 transition flex items-center justify-center gap-1.5"
              >
                <span>Thực hiện ngay</span>
                <i className="bi bi-arrow-right-short text-base leading-none"></i>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* 5. MODAL THÊM / SỬA CA HỌC */}
      {showItemModal && (
        <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-xs flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-3xl p-5 w-full max-w-sm shadow-xl border border-slate-100 animate-in zoom-in-95 duration-150">
            <div className="flex items-center justify-between mb-3 border-b pb-2">
              <h4 className="font-black text-sm text-slate-900 m-0">
                {editingItem ? "Chỉnh Sửa Ca Học" : "Thêm Ca Học Mới"}
              </h4>
              <button
                onClick={() => setShowItemModal(false)}
                className="w-7 h-7 rounded-full bg-slate-100 flex items-center justify-center border-0 text-slate-500 hover:bg-slate-200 cursor-pointer"
              >
                <i className="bi bi-x-lg text-xs"></i>
              </button>
            </div>

            <form onSubmit={handleSaveItem} className="space-y-3 text-xs font-bold text-slate-700">
              <div>
                <label className="block mb-1 text-[11px]">Tiêu đề ca học / bài tập</label>
                <input
                  type="text"
                  required
                  value={formData.title}
                  onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                  placeholder="Ví dụ: Ôn tập 10 câu trắc nghiệm..."
                  className="w-full px-3 py-2 rounded-xl border border-slate-200 focus:outline-[#0b57d0] text-xs font-semibold"
                />
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="block mb-1 text-[11px]">Khung giờ</label>
                  <input
                    type="text"
                    value={formData.timeSlot}
                    onChange={(e) => setFormData({ ...formData, timeSlot: e.target.value })}
                    placeholder="19:30 - 20:15"
                    className="w-full px-3 py-2 rounded-xl border border-slate-200 focus:outline-[#0b57d0] text-xs font-semibold"
                  />
                </div>
                <div>
                  <label className="block mb-1 text-[11px]">Thời lượng (phút)</label>
                  <input
                    type="number"
                    value={formData.durationMinutes}
                    onChange={(e) => setFormData({ ...formData, durationMinutes: e.target.value })}
                    className="w-full px-3 py-2 rounded-xl border border-slate-200 focus:outline-[#0b57d0] text-xs font-semibold"
                  />
                </div>
              </div>

              <div>
                <label className="block mb-1 text-[11px]">Hình thức rèn luyện</label>
                <select
                  value={formData.taskType}
                  onChange={(e) => setFormData({ ...formData, taskType: e.target.value })}
                  className="w-full px-3 py-2 rounded-xl border border-slate-200 focus:outline-[#0b57d0] text-xs bg-white font-semibold"
                >
                  <option value="quiz">Luyện đề trắc nghiệm (Quiz)</option>
                  <option value="doc_study">Nghiên cứu giáo trình (Tài liệu)</option>
                  <option value="flashcard">Thẻ ghi nhớ (Flashcard)</option>
                </select>
              </div>

              <div>
                <label className="block mb-1 text-[11px]">Mô tả chi tiết</label>
                <textarea
                  rows="2"
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  placeholder="Ghi chú kiến thức hoặc mục tiêu..."
                  className="w-full px-3 py-2 rounded-xl border border-slate-200 focus:outline-[#0b57d0] text-xs font-semibold"
                />
              </div>

              <div className="flex gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setShowItemModal(false)}
                  className="flex-1 py-2 rounded-xl bg-slate-100 text-slate-600 font-bold border-0 cursor-pointer"
                >
                  Hủy
                </button>
                <button
                  type="submit"
                  className="flex-1 py-2 rounded-xl bg-[#0b57d0] text-white font-bold border-0 cursor-pointer shadow-xs active:scale-95 transition"
                >
                  {editingItem ? "Lưu thay đổi" : "Thêm ca học"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default TimelinePage;  